"""Generate ``workflow/schemas/config.schema.yaml`` from :class:`RegulonadoConfig`.

``RegulonadoConfig.model_json_schema()`` already emits everything Snakemake's
``validate()`` needs — ``additionalProperties``, ``required``, ``$defs``, and
per-field ``default`` values (which drive Snakemake's default-filling) — so
hand-mirroring the schema is no longer necessary, and would only drift from
the models again. Run ``python -m regulonado.config.schema_gen`` to
regenerate; CI checks that regenerating produces no diff.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from regulonado.config.models import RegulonadoConfig

SCHEMA_PATH = Path(__file__).resolve().parents[1] / "workflow" / "schemas" / "config.schema.yaml"
_HEADER = (
    "# Generated by `python -m regulonado.config.schema_gen` from RegulonadoConfig.\n"
    "# Do not hand-edit — regenerate instead; CI checks this file has no diff.\n"
)


def _is_optional_object_ref(subschema: dict) -> bool:
    """True for ``SomeModel | None`` fields: an ``anyOf`` of a ``$ref`` and ``null``."""
    branches = subschema.get("anyOf")
    if not branches:
        return False
    return any("$ref" in branch for branch in branches) and any(
        branch.get("type") == "null" for branch in branches
    )


def _drop_optional_object_defaults(schema: dict) -> None:
    """Strip ``default: null`` from optional nested-model fields, in place.

    Snakemake's ``validate()`` fills defaults via a custom jsonschema
    extension that applies a property's own ``properties`` keyword to fill
    *its* defaults — unconditionally, even when the instance is ``None``
    (design/attribution are absent unless configured). That crashes with
    ``AttributeError: 'NoneType' object has no attribute 'setdefault'``.
    These fields need no default-filling anyway: absent already means
    "not configured", which is exactly what the pydantic model does too.
    """
    for definition in schema.get("$defs", {}).values():
        for subschema in definition.get("properties", {}).values():
            if _is_optional_object_ref(subschema):
                subschema.pop("default", None)
    for subschema in schema.get("properties", {}).values():
        if _is_optional_object_ref(subschema):
            subschema.pop("default", None)


def generate_schema() -> dict:
    """Return the JSON Schema Snakemake's ``validate()`` should enforce."""
    schema = RegulonadoConfig.model_json_schema()
    _drop_optional_object_defaults(schema)
    return {"$schema": "https://json-schema.org/draft/2020-12/schema", **schema}


def render_schema() -> str:
    return _HEADER + yaml.safe_dump(generate_schema(), sort_keys=False, default_flow_style=False)


def write_schema(path: Path = SCHEMA_PATH) -> None:
    path.write_text(render_schema())


if __name__ == "__main__":
    write_schema()
    print(f"Wrote {SCHEMA_PATH}")
